{% set version = "0.4.0" %}

package:
    name: siphon
    version: {{ version }}

source:
    fn: siphon-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/s/siphon/siphon-{{ version }}.tar.gz
    md5: 19a24db825cba554af10c89b8d7aff64

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - protobuf >=3.0.0a3
        - requests
        - netcdf4
        - enum34  # [py27]

test:
    imports:
        - siphon
        - siphon.cdmr
        - siphon.catalog
        - siphon.ncss
        - siphon.radarserver

about:
    home: https://github.com/Unidata/siphon
    license: MIT License
    summary: 'A collection of Python utilities for interacting with the Unidata technology stack.'

extra:
    recipe-maintainers:
        - ocefpaf
        - dopplershift
